version: '3'
services:
  api:
    image: pfe_backend
    container_name: PFEProject
    environment:
      SPRING_APPLICATION_JSON: '{
            "server.port" : "$SPRING_LOCAL_PORT",
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
    volumes:
      - app_data:/app/data


  mysqldb:
    container_name: mysqldb
    image: mysql:latest  # You can use a different version if needed
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"  # Map MySQL's port to the host

    volumes:
      - db:/var/lib/mysql

volumes:
  app_data:
  db: