version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ziedhechmi/pfe_backend
    container_name: pfe_backend
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/restitution?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_DATA_MONGODB_URI=mongo://mongo-db:27017/Controlleur
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - MANAGEMENT.ENDPOINTS.WEB.EXPOSURE.INCLUDE=*
      - MANAGEMENT.ENDPOINT.PROMETHEUS.ENABLED=true
      - MANAGEMENT.ENDPOINT.METRICS.ENABLED=true
      - management.endpoint.health.show-details=always
      - SPRING_DATA_MONGODB_USERNAME=admin
      - SPRING_DATA_MONGODB_PASSWORD=adminpassword
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - mysql-db
      - mongo-db
  mysql-db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=restitution
    ports:
      - 3306:3306
    volumes:
      - db_data_mysql:/var/lib/mysql
    container_name: mysql_db

  mongo-db:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/mongo
    container_name: mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword

volumes:
  db_data_mysql:
  db:
  mongodb_data: