server:
    servlet:
        context-path: /Stage
    port: 8082

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/restitution?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password:


    data:
        mongodb:
            host: localhost
            port: 27017
            database: Controlleur


    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect

    mail:
        host: smtp.gmail.com
        port: 587
        username: b3chir.ferjani@gmail.com
        password: hwrf zsrp mlaf zjlr
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true


application:
    application:
        jwt:
            secret-key: 576E5A7234753778214125442A472D4B6150645367556B58703273357638792F
            expiration: 86400000
            refresh-token:
                expiration: 604800000




management:
    endpoints:
        web:
            exposure:
                include: "*"
        prometheus:
            enabled: true
    endpoint:
        metrics:
            enabled: true
        health:
            show-details: always

